server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri: https://github.com/beikeak4/myorderingsystem.git
          searchPaths: config #仓库路径
          label: master #仓库的分支
#          username: 2056626751@qq.com #git仓库用户名
#          password: hongtougongbei1@ #git仓库密码


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/